module.exports = {
  extends: 'airbnb',
  parser: 'babel-eslint',
  rules: {
    'camelcase': 'off',
    'class-methods-use-this': 'off',
    'import/extensions': 'off',
    'import/first': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 'off',
    'import/prefer-default-export': 'off',
    'max-len': ['warn', 120, 4],
    'no-multiple-empty-lines': ['error', { max: 1 }],
    'no-nested-ternary': 'off',
    'no-plusplus': 'off',
    'no-sequences': 'off',
    'react/forbid-prop-types': 'off',
    'react/jsx-filename-extension': 'off',
    'react/no-find-dom-node': 'off',
    semi: ['error', 'never'],

    // BOOH
    'import/newline-after-import': 'off',
    'import/no-named-as-default': 'off',
    'import/no-webpack-loader-syntax': 'off',
    'jsx-a11y/anchor-has-content': 'off',
    'jsx-a11y/href-no-hash': 'off',
    'jsx-a11y/label-has-for': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'no-cond-assign': 'off',
    'no-continue': 'off',
    'no-else-return': 'off',
    'no-mixed-operators': 'off',
    'no-new-func': 'off',
    'no-new-wrappers': 'off',
    'no-param-reassign': 'off',
    'no-prototype-builtins': 'off',
    'no-restricted-properties': 'off',
    'no-restricted-syntax': 'off',
    'no-shadow': 'off',
    'no-template-curly-in-string': 'off',
    'no-underscore-dangle': 'off',
    'no-unused-expressions': 'off',
    'no-use-before-define': 'off',
    'react/jsx-no-target-blank': 'off',
    'react/no-string-refs': 'off',
    'react/no-unused-prop-types': 'off',
    'react/prefer-stateless-function': 'off',
  },
  plugins: [
    'babel',
  ],
};
